version: "2.1"

volumes:
  dashboard-data:

services:
  dashboard:
    image: balenablocks/dashboard
    restart: always
    volumes:
      - "dashboard-data:/data"
    ports:
      - "8080:80"
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
  connector:
    image: balenablocks/connector:raspberrypi3
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
    privileged: true # necessary to change container hostname
    ports:
      - "8080" # only necessary if using ExternalHttpListener (see below)    