version: '3'
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud:version-22.1.1
    container_name: nextcloud
    volumes:
      - ${DATA_PATH}/nextcloud/config:/config
      - ${DATA_PATH}/nextcloud/data:/data
      - ${DATA_PATH}/share:/share
    ports:
      - 443:443
