#!/usr/bin/env bash

# config location
CONF_PATH=$HOME/.config/polybar

# Check WM
cur_wm=i3

echo "WM is $cur_wm... Launching appropriate bars"

if [[ $cur_wm == i3 ]]; then  # if i3 launch the i3-bar
  polybar -r --config=$CONF_PATH/config i3-bar &

fi

